# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    build_number = ENV['GITHUB_RUN_NUMBER'] || '1'
    
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    sh "flutter build apk --release \
    --flavor production \
    --target lib/main_production.dart \
    --build-number=#{build_number} \
    --no-tree-shake-icons"

    firebase_app_distribution(
    app: "1:467868122378:android:a4643c2fe1ba67265b8ef3",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "omniamahmoud912019@gmail.com",
    release_notes: "Test GitHub Action Release"
    
  )
  end
end
